### ISSUE TITLE
sidebar 

### ISSUE THREAD

**Issue by AM-77** [boussadjra/vueye#1]
I think that the images are self expressive. 

browser: chrome

![2021-01-15 12 19 17 vite-wind netlify app cdeca3a1f770](https://user-images.githubusercontent.com/18232579/104719457-c332dc80-572c-11eb-9e1c-7383661a5a4d.png)
![2021-01-15 12 19 47 vite-wind netlify app 94a2a82a663a](https://user-images.githubusercontent.com/18232579/104719473-ca59ea80-572c-11eb-9b1b-82beb1e89232.png)

if you need more details, I would be happy to help.
good luck.

**Comment by boussadjra** [comment]
thank you very much, Actually this is a starter it's not working perfectly and it has not documented yet,  but I want to improve the responsiveness and some color issues, you're welcome to help and to test
